#!/usr/bin/env python3
"""Generate Dockerfile.v4: fully self-contained image. All models baked as <=3GB chunk
layers (docker retries survive small layers; boot_v4.sh reassembles once at first run)."""
import json, urllib.request, math

CHUNK = 3 * 1024**3
HF = "https://huggingface.co/{repo}/resolve/main/{path}"
FILES = [  # (repo, path)
    ("Comfy-Org/MiniMax-H3", "diffusion_models/minimax_h3_fl2va_pruned_int8_convrot.safetensors"),
    ("Comfy-Org/MiniMax-H3", "diffusion_models/minimax_h3_ref2va_pruned_int8_convrot.safetensors"),
    ("Comfy-Org/MiniMax-H3", "text_encoders/qwen3vl_32b_minimax_h3_nvfp4_awq.safetensors"),
    ("Comfy-Org/MiniMax-H3", "vae/minimax_h3_video_vae_fp16.safetensors"),
    ("Comfy-Org/MiniMax-H3", "vae/minimax_h3_audio_vae_fp32.safetensors"),
    ("larryvrh/MiniMax-H3-Turbo-Lora", "minimax_h3_turbo_v4_step600_ema.safetensors"),
]

def size_of(url):
    req = urllib.request.Request(url, method="HEAD", headers={"User-Agent": "curl/8"})
    with urllib.request.urlopen(req, timeout=60) as r:
        return int(r.headers["Content-Length"])

manifest = []
lines = [
    "# v4: SINGLE self-contained image — env + ALL models (fl2va/ref2va int8, nvfp4 CLIP, VAEs, turbo LoRA)",
    "# + all nodes (Turbo, Director). Models split into <=3GB chunk layers (pull-retry survivable);",
    "# boot_v4.sh reassembles at first boot. Generated by gen_dockerfile_v4.py — DO NOT EDIT BY HAND.",
    "FROM vastai/pytorch:2.12.0-cu130-cuda-13.2-mini-py312-2026-06-15",
    "RUN ln -sf $(command -v python3) /usr/local/bin/python && (apt-get update -qq && apt-get install -y -qq aria2 || true)",
    "RUN git clone --depth 1 https://github.com/comfyanonymous/ComfyUI.git /workspace/ComfyUI",
    "RUN pip install -q -r /workspace/ComfyUI/requirements.txt && \\",
    "    pip install -q sageattention huggingface_hub scenedetect opencv-python-headless imageio-ffmpeg",
    "RUN git clone --depth 1 https://github.com/larryvrh/ComfyUI-MiniMax-H3-Turbo /workspace/ComfyUI/custom_nodes/ComfyUI-MiniMax-H3-Turbo && \\",
    "    git clone --depth 1 https://github.com/AIMixer/ComfyUI_MiniMaxH3_Director /workspace/ComfyUI/custom_nodes/ComfyUI_MiniMaxH3_Director",
]
for repo, path in FILES:
    url = HF.format(repo=repo, path=path)
    total = size_of(url)
    name = path.split("/")[-1]
    n = math.ceil(total / CHUNK)
    manifest.append({"path": path if repo.endswith("MiniMax-H3") else "loras/" + name,
                     "name": name, "size": total, "chunks": n})
    for i in range(n):
        a, b = i * CHUNK, min((i + 1) * CHUNK, total) - 1
        lines.append(f'RUN mkdir -p /workspace/parts && curl -fSL --retry 8 --retry-all-errors -r {a}-{b} "{url}" -o /workspace/parts/{name}.p{i:02d}')
print("chunk plan:")
for m in manifest:
    print(f"  {m['name']}: {m['size']/1e9:.1f}GB -> {m['chunks']} chunks")
lines += [
    "COPY cloud_gen.py boot_v4.sh parts_manifest.json /workspace/h/",
    "RUN chmod +x /workspace/h/boot_v4.sh",
    "ENV GW=1312 GH=736 GF=141 GSTEPS=20 GN=0 GTURBO=0",
]
open("Dockerfile.v4", "w").write("\n".join(lines) + "\n")
json.dump(manifest, open("parts_manifest.json", "w"), indent=1)
print(f"Dockerfile.v4 written ({len(lines)} lines), parts_manifest.json written")
